### ISSUE TITLE
Apple Music is broken

### ISSUE THREAD

**Issue by aleclol** [Topis-Lavalink-Plugins/Topis-Source-Managers#5]
Apple has implemented an origin lock on the API key used by the Apple Music web client.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/50505980/161618155-380f51c8-860c-454b-a8f8-4b5ddd338b37.png">

Simply setting the `Origin` header to `https://music.apple.com` when sending API requests will fix this issue.

Without the header, all requests to the API fail and therefore, all track/album/playlist/artist lookups fail

**Comment by aleclol** [comment]
I can send in a PR to fix this but it might be a little bit since I don't know Java so I'll need to do a little bit of reading on the HTTP client used.

**Comment by TopiSenpai** [comment]
ah nice fix lol

**Comment by TopiSenpai** [comment]
I'll do it myself thx!

**Comment by TopiSenpai** [comment]
should be fixed in <https://github.com/Topis-Lavalink-Plugins/Topis-Source-Managers/commit/624744e7e05602df22746588df79cd730c2e891c>

**Comment by aleclol** [comment]
Fixed in #3
